### ISSUE TITLE
Create Template

### ISSUE THREAD

**Issue by jricher** [mitreid-connect/trust-framework#1]
Create a template form of the document that can be filled in with variable values for items like the primary organization and any party that signs onto the agreement (or is signed on by a user)

**Comment by dazzaji** [comment]
Is there a template approach that is well suited for the technical environment?  Some of the Human Dynamics team showed me ways to do legal templates for form-fill contract formation using Python.  Would something in Java be a better fit for the source code, or is there some other language or process you might prefer?

**Comment by jricher** [comment]
I wasn't thinking in terms of anything specific to a given programming language, but rather a more generic means to say "VALUE-X GOES HERE". There are a number of approaches and I wouldn't be surprised if there's already a good one that uses Markdown as its basis.

**Comment by dazzaji** [comment]
I think the current outline file we are using addresses the initial semantic aspect and content model generally by way of the headers and subheaders.  The automation tool to pop the content from a field into a template could use python, applying a human dynamics automated agreement and license design pattern in our human dynamics repository.  I'll dig it out and link to it for evaluation.  

Also, there are a couple GitHub anchored legal contract oriented companies that have figured out reliable processes for this task.  I will track them down (some of them presented at a Brooklyn Law School digital law event in April ... I'll investigate and link to any promising and openly available solutions I find).

Are there other approaches for this document assembly automation process that anybody favors?

**Comment by dazzaji** [comment]
Hi Ray -- For fillable templates that are wizard drive, I am working now with the new: http://www.qnamarkup.org/  It can also output PDF and it's all open source.  This weekend we'll add esignature capability at a prototype jam event (next step will be eNotarization).  The MITRE approach was not so much a template fill/wizard project - it followed more of a "package" orientation like you see with open source operating systems.
